<?php
/**
 * @file
 * Customizing the registration process for the TCDrupal website.
 */

/**
 * Implements hook_registration_presave().
 */
function tcdrupalregistrationtweaks_registration_presave(Registration $registration) {
  // Check to make sure this is a new registration entity and that it's being
  // created by one user on behalf of another person. Then, we can create an
  // account for the "other person" and re-assign the registration to them.
  if ($registration->is_new == TRUE && isset($registration->anon_mail)) {
    $email = $registration->anon_mail;

    // See if there is already a user with this email address.
    $account = user_load_by_mail($email);

    if (!$account) {
      // Generate a new user account for the person this registration is for.
      $user = array(
        'is_new' => TRUE,
        'name' => $email,
        'mail' => $email,
        'pass' => user_password(),
        'status' => 1,
      );
      $account = user_save(NULL, $user);
    }

    // Change the registration so that it belongs to the new account.
    $registration->user_uid = $account->uid;
    $registration->anon_mail = NULL;

    // Then make sure we send them the account registration email.
    _user_mail_notify('register_no_approval_required', $account);
  }
}

/**
 * Implements hook_form_alter().
 */
function tcdrupalregistrationtweaks_form_alter(&$form, &$form_state, $form_id) {
  // Hide the shirt size field on the normal entity registration form.
  if ($form_id == 'registration_form' && isset($form['#entity'])) {
    // The commerce_product entity with ID of 14 is the individual sponsorship
    // product. If this registration is NOT associated with the sponsorship
    // product we need to hide the shirt size field.
    if ($form['#entity']->entity_id != 14 && $form['#entity']->entity_type == 'commerce_product') {
      $form['field_reg_shirt_size']['#access'] = FALSE;
    }
  }

  // Hide the shirt size field during checkout.
  if ($form_id == 'commerce_checkout_form_registration') {
    if (isset($form['registration_information']['prod-TCDRUPAL2014'])) {
      foreach ($form['registration_information']['prod-TCDRUPAL2014'] as $key => $element) {
        $form['registration_information']['prod-TCDRUPAL2014'][$key]['field_reg_shirt_size']['#access'] = FALSE;
      }
    }
  }
}

/**
 * Implements hook_user_view().
 *
 * Add information about a user's registration(s) to their account profile page.
 */
function tcdrupalregistrationtweaks_user_view($account, $view_mode, $langcode) {
  global $user;

  if ($user->uid === $account->uid || user_access('administer users')) {
    // Get a list of all of the registration entities associated with this user.
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'registration');
    $query->propertyCondition('user_uid', $account->uid);
    $rids = $query->execute();

    // If there are any associated registrations list them with link to the edit
    // page for that registration.
    if (isset($rids['registration'])) {
      $rids = array_keys($rids['registration']);
      $registrations = registration_load_multiple($rids);

      // Build a list of links.
      $registration_links = array();
      foreach ($registrations as $registration) {
        // Load the host entity so we can get it's title.
        $host_entity = entity_load_single($registration->entity_type, $registration->entity_id);
        $registration_links[] = l(t('Registration for @title', array('@title' => $host_entity->title)), 'registration/' . $registration->registration_id . '/edit');
      }

      // If we have links add them to the user's profile page, otherwise skip
      // the listing.
      $registration_edit = array();
      if (count($registration_links) >= 1) {
        $registration_edit['registration-' . $registration->registration_id] = array(
          'heading' => array(
            '#type' => 'markup',
            '#markup' => t('<h3>Registration info</h3>'),
          ),
          'links' => array(
            '#theme' => 'item_list',
            '#items' => $registration_links,
          ),
          'after' => array(
            '#markup' => '<p>You can edit your registration information at any time by clicking the links above.</p>',
          ),
        );
      }
      $account->content['registrations'] = $registration_edit;
      $account->content['registrations']['#weight'] = -100;
    }
  }
}
